export default {
  "HARAKAT_TYPE": ["fathah", "kasrah", "dhammah"],
  "TANWIN_TYPE": ["fathatain", "kasratain", "dhammatain"],
  "HARAKAT": { "fathah": "\u064E", "fathatain": "\u064B", "kasrah": "\u0650", "kasratain": "\u064D", "dhammah": "\u064F", "dhammatain": "\u064C" },
  "HARAKAT_LATIN": { "fathah": "a", "fathatain": "an", "kasrah": "i", "kasratain": "in", "dhammah": "u", "dhammatain": "un" },
  "COLOR": ["#E65727", "#F29100", "#47A334", "#1296C2", "#AB67C2", "#DB69A2"],
  "HURUF" : [
    { "id": 1, "arb": "ا", "uni": "\u0627", "ltn": "", "trs": "alif" },
    { "id": 2, "arb": "ب", "uni": "\u0628", "ltn": "b", "trs": "ba" },
    { "id": 3, "arb": "ت", "uni": "\u062A", "ltn": "t", "trs": "ta" },
    { "id": 4, "arb": "ث", "uni": "\u062B", "ltn": "ts", "trs": "tsa" },
    { "id": 5, "arb": "ج", "uni": "\u062C", "ltn": "j", "trs": "jim" },
    { "id": 6, "arb": "ح", "uni": "\u062D", "ltn": "ḥ", "trs": "ḥa" },
    { "id": 7, "arb": "خ", "uni": "\u062E", "ltn": "kh", "trs": "kha" },
    { "id": 8, "arb": "د", "uni": "\u062F", "ltn": "d", "trs": "dal" },
    { "id": 9, "arb": "ذ", "uni": "\u0630", "ltn": "dz", "trs": "dzal" },
    { "id": 10, "arb": "ر", "uni": "\u0631", "ltn": "r", "trs": "ra" },
    { "id": 11, "arb": "ز", "uni": "\u0632", "ltn": "z", "trs": "zai" },
    { "id": 12, "arb": "س", "uni": "\u0633", "ltn": "s", "trs": "sin" },
    { "id": 13, "arb": "ش", "uni": "\u0634", "ltn": "sy", "trs": "syin" },
    { "id": 14, "arb": "ص", "uni": "\u0635", "ltn": "ṣh", "trs": "ṣhad" },
    { "id": 15, "arb": "ض", "uni": "\u0636", "ltn": "ḍh", "trs": "ḍhad" },
    { "id": 16, "arb": "ط", "uni": "\u0637", "ltn": "ṭh", "trs": "ṭha" },
    { "id": 17, "arb": "ظ", "uni": "\u0638", "ltn": "ẓh", "trs": "ẓha" },
    { "id": 18, "arb": "ع", "uni": "\u0639", "ltn": "ʿ", "trs": "ʻain" },
    { "id": 19, "arb": "غ", "uni": "\u063A", "ltn": "gh", "trs": "ghain" },
    { "id": 20, "arb": "ف", "uni": "\u0641", "ltn": "f", "trs": "fa" },
    { "id": 21, "arb": "ق", "uni": "\u0642", "ltn": "q", "trs": "qaf" },
    { "id": 22, "arb": "ك", "uni": "\u0643", "ltn": "k", "trs": "kaf" },
    { "id": 23, "arb": "ل", "uni": "\u0644", "ltn": "l", "trs": "lam" },
    { "id": 24, "arb": "م", "uni": "\u0645", "ltn": "m", "trs": "mim" },
    { "id": 25, "arb": "ن", "uni": "\u0646", "ltn": "n", "trs": "nun" },
    { "id": 26, "arb": "و", "uni": "\u0648", "ltn": "w", "trs": "wau" },
    { "id": 27, "arb": "ه", "uni": "\u0647", "ltn": "h", "trs": "ha" },
    { "id": 28, "arb": "لا", "uni": "\u0644\u0627", "ltn": "-", "trs": "lam alif" },
    { "id": 29, "arb": "ء", "uni": "\u0621", "ltn": "-", "trs": "hamzah" },
    { "id": 30, "arb": "ي", "uni": "\u064A", "ltn": "y", "trs": "ya" }
  ]
}